### Hi :)

In [1]:
# imports
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import torch
import numpy as np
from tqdm import tqdm
from itertools import product # used for hyperparameter grid search, unused if not doing hyperparameter tuning
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
seed = 42 # for reproducibility
torch.manual_seed(seed)

data = pd.read_csv('data.csv', delimiter=';')
data

RECORDING_SESSION_LABEL  trial  IA_ID  item  list      IA_LABEL  \
0                     10m23r2     12      1     1     2          Viel   
1                     10m23r2     12      2     1     2          Geld   
2                     10m23r2     12      3     1     2         wurde   
3                     10m23r2     12      4     1     2   investiert,   
4                     10m23r2     12      5     1     2         bevor   
...                       ...    ...    ...   ...   ...           ...   
11171                  9m23r1     10     12    28     1  Verteidigung   
11172                  9m23r1     10     13    28     1       Europas   
11173                  9m23r1     10     14    28     1        erhöht   
11174                  9m23r1     10     15    28     1        werden   
11175                  9m23r1     10     16    28     1      sollten.   

       wordlength condition  is_critical  is_spill1  ...  duration_firstpass  \
0               4      none            0          0  ...                 236   
1               4      none            0          0  ...                 424   
2               5      none            0          0  ...                   0   
3              11      none            0          0  ...                 420   
4               5      none            0          0  ...                 296   
...           ...       ...          ...        ...  ...                 ...   
11171          12    filler            0          0  ...                 168   
11172           7      none            0          0  ...                 224   
11173           6      none            0          0  ...                 332   
11174           6      none            0          0  ...                 244   
11175           8      none            0          0  ...                 160   

       duration_firstfixation  fix_count    avg_pupil  IA_REGRESSION_IN_COUNT  \
0                         236          1  1408.000000                       0   
1                         264          3  1379.333333                       2   
2                           0          0     0.000000                       0   
3                         268          3  1290.000000                       1   
4                         296          2  1242.500000                       1   
...                       ...        ...          ...                     ...   
11171                     168          2   497.000000                       0   
11172                     224          1   493.000000                       0   
11173                     332          1   472.000000                       0   
11174                     244          1   477.000000                       0   
11175                     160          1   495.000000                       0   

       IA_REGRESSION_OUT_COUNT  saccade_length  saccade_duration  \
0                            0       72.376792                16   
1                            0       71.519648               160   
2                            1        0.000000                 0   
3                            0       65.401223                12   
4                            0       42.311819                12   
...                        ...             ...               ...   
11171                        0       91.810675                20   
11172                        0      119.788355                24   
11173                        0       95.117033                20   
11174                        0       58.649126                16   
11175                        1        0.000000                 0   

       go_past_time  sentenceCondition  
0               236            control  
1               424            control  
2                 0            control  
3               420            control  
4               296            control  
...             ...                ...  
11171           168             filler  
11172           224             filler  
11173    

In [2]:
print(data["RECORDING_SESSION_LABEL"].unique())

['10m23r2' '11w20l3' '13w53r1' '14w19l2' '15w20r3' '16m20l4' '17w24r1'
 '18w19l2' '19w21l3' '20w20r4' '21m29l1' '22m23r2' '23w24r3' '24w22r4'
 '25m23l1' '26m18l2' '28m3r4' '29w22r1' '2m22r2' '30w22r4' '31m20r4'
 '32w22l1' '33w35r3' '34m23r3' '35m24l2' '3m25r3' '4f21r4' '5f22r1'
 '6m129r2' '7m21l3' '8m22l4' '9m23r1']


In [3]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __getitem__(self, index):
        features = self.features.iloc[index].to_numpy()
        label = self.labels.iloc[index]
        return features, label

    def __len__(self):
        return len(self.features)

In [4]:
def split_data(data, batch_size, task, alpha):
    
    dataloaders = []
    pos_weights = []
    # global class_weights

    if task == 0 or task == 1: # Known subjects and items
        features, labels = data
        dataset = CustomDataset(features, labels)
        n = len(dataset)
        if task == 0:
            k = 10 # k-fold cross-validation
        elif task == 1:
            k = n # leave-one-out cross-validation
        fold_size = n // k
        folds = []
        for i in range(k):
            start = i * fold_size
            end = (i + 1) * fold_size if i < k - 1 else n
            folds.append(torch.utils.data.Subset(dataset, range(start, end)))

        for i in range(k):
            # splits for cross-validation, validation set = test set (since we're doing k-fold, we won't use a separate test set)
            validation_dataset = folds[i]
            t = i + 1 if i < k - 1 else 0
            test_dataset = folds[t]
            train_folds = [folds[j] for j in range(k) if j != i]# and j != t]
            train_dataset = torch.utils.data.ConcatDataset(train_folds)

            # class weights for weighted cross-entropy loss (to handle class imbalance)
            y = torch.tensor([label for _, label in train_dataset], dtype=torch.long)
            sum = y.sum().item()
            weight = alpha*(len(train_dataset)-sum) / sum
            pos_weights.append(torch.tensor(weight, dtype=torch.float))

            train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
            validation_dataloader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=True)
            test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
            dataloaders.append((train_dataloader, validation_dataloader, test_dataloader))
            #dataloaders.append((train_dataloader, validation_dataloader))

        return dataloaders, pos_weights
    
    elif task == 2: # Held-out subjects, known items
        test_items_count = 0
        subject_ids = list(data.groups.keys())

        for i in range(0, len(subject_ids), 2):
            subject_indexes = [i, i+1]
            subjects = [subject_ids[subject_index] for subject_index in subject_indexes]

            others = [subject for j, subject in enumerate(subject_ids) if j != i and j != i+1]

            test = pd.concat([data.get_group(subject) for subject in subjects])
            test_items_count += len(test)
            train_eval = pd.concat([data.get_group(subject) for subject in others])
            shuffled = train_eval.sample(frac = 1, random_state=seed) # shuffle the data -> wrecked.
            
            # splitting data into features and labels for dataset creation
            test_labels = test["condition"].copy()
            test_features = test.copy().drop(["condition", "sentenceCondition", "RECORDING_SESSION_LABEL", "item"], axis=1)
            test_dataset = CustomDataset(test_features, test_labels)
            
            train_eval_labels = shuffled["condition"].copy()
            train_eval_features = shuffled.copy().drop(["condition", "sentenceCondition", "RECORDING_SESSION_LABEL", "item"], axis=1)
            train_eval_dataset = CustomDataset(train_eval_features, train_eval_labels)


            train_eval_split = 0.9
            train_size = int(train_eval_split * len(train_eval_dataset))
            validation_size = len(train_eval_dataset) - train_size
            train_dataset, validation_dataset = torch.utils.data.random_split(train_eval_dataset, [train_size, validation_size])

            # class weights for weighted cross-entropy loss (to handle class imbalance)
            y = torch.tensor([label for _, label in train_dataset], dtype=torch.long)
            sum = y.sum().item()
            weight = alpha*(len(train_dataset)-sum) / sum
            pos_weights.append(torch.tensor(weight, dtype=torch.float))

            train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
            validation_dataloader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=True)
            test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
            dataloaders.append((train_dataloader, validation_dataloader, test_dataloader))
        return dataloaders, pos_weights
    
    elif task == 3: # Held-out items, known subjects
        test_items_count = 0
        for i, item in enumerate(data.groups.keys()):
            test = data.get_group(item)
            test_items_count += len(test)
            train_eval = pd.concat([data.get_group(i) for i in data.groups.keys() if i != item])
            shuffled = train_eval.sample(frac = 1, random_state=seed) # shuffle the data -> wrecked.
            
            # splitting data into features and labels for dataset creation
            test_labels = test["condition"].copy()
            test_features = test.copy().drop(["condition", "sentenceCondition", "RECORDING_SESSION_LABEL", "item"], axis=1)
            test_dataset = CustomDataset(test_features, test_labels)
            
            train_eval_labels = shuffled["condition"].copy()
            train_eval_features = shuffled.copy().drop(["condition", "sentenceCondition", "RECORDING_SESSION_LABEL", "item"], axis=1)
            train_eval_dataset = CustomDataset(train_eval_features, train_eval_labels)


            train_eval_split = 0.9
            train_size = int(train_eval_split * len(train_eval_dataset))
            validation_size = len(train_eval_dataset) - train_size
            train_dataset, validation_dataset = torch.utils.data.random_split(train_eval_dataset, [train_size, validation_size])

            # class weights for weighted cross-entropy loss (to handle class imbalance)
            y = torch.tensor([label for _, label in train_dataset], dtype=torch.long)
            sum = y.sum().item()
            weight = alpha*(len(train_dataset)-sum) / sum
            pos_weights.append(torch.tensor(weight, dtype=torch.float))

            train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
            validation_dataloader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=True)
            test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
            dataloaders.append((train_dataloader, validation_dataloader, test_dataloader))
        return dataloaders, pos_weights
    else:
        raise ValueError("Task argument must be either 1, 2, or 3")

    


In [5]:
def preprocess_and_split_data(data, batch_size, task, alpha):
    
# all tasks
    
    data_copy = data.loc[data['is_critical'] == 1].copy()
    dropped = data_copy.drop(['composite', 'LF', 'HF', "IA_ID", "trial", "list", "IA_LABEL", "wordlength", "is_critical", 
                'is_spill1', 'is_spill2', 'is_spill3', 'filler', 'function_word', 'other_filler'], axis=1)

    # normalizing input features beforehand, increased performance vs adding batchnorm layer to model
    temp = dropped[['fixation_duration',
        'duration_firstpass', 'duration_firstfixation', 'fix_count',
        'avg_pupil', 'IA_REGRESSION_IN_COUNT', 'IA_REGRESSION_OUT_COUNT',
        'saccade_length', 'saccade_duration', 'go_past_time']]
    temp = (temp - temp.mean()) / temp.std()
    dropped[['fixation_duration',
        'duration_firstpass', 'duration_firstfixation', 'fix_count',
        'avg_pupil', 'IA_REGRESSION_IN_COUNT', 'IA_REGRESSION_OUT_COUNT',
        'saccade_length', 'saccade_duration', 'go_past_time']] = temp
    normalized = dropped
    # mapping condition and sentenceCondition to 0 and 1 for critical word classification
    normalized[["condition", "sentenceCondition"]] = normalized[["condition", "sentenceCondition"]].map(lambda x: x.replace("none", "0"))
    normalized[["condition", "sentenceCondition"]] = normalized[["condition", "sentenceCondition"]].map(lambda x: x.replace("control", "0"))
    normalized[["condition", "sentenceCondition"]] = normalized[["condition", "sentenceCondition"]].map(lambda x: x.replace("pseudo", "1"))
    normalized[["condition", "sentenceCondition"]] = normalized[["condition", "sentenceCondition"]].map(lambda x: x.replace("filler", "0"))
    normalized[["condition", "sentenceCondition"]] = normalized[["condition", "sentenceCondition"]].astype(int)
    mapped = normalized

# task 1 specific steps
    if task == 0 or task == 1: # Known subjects and items
        shuffled = mapped.sample(frac = 1, random_state=seed) # shuffle the data -> wrecked.
        # splitting data into features and labels for dataset creation
        labels = shuffled["condition"].copy()
        features = shuffled.copy().drop(["condition", "sentenceCondition", "RECORDING_SESSION_LABEL", "item"], axis=1)
        data = (features, labels)
        return split_data(data, batch_size, task, alpha)
    
    elif task == 2: # Held-out subjects, known items
        subjects = mapped.groupby('RECORDING_SESSION_LABEL')
        return split_data(subjects, batch_size, task, alpha)
    elif task == 3: # Held-out items, known subjects
        items = mapped.groupby('item')
        return split_data(items, batch_size, task, alpha)
    else:
        raise ValueError("Task argument must be either 1, 2, or 3")

In [6]:
def train_test(model, dataloader, optimizer, pos_weight, training="train"):
   
    loss_function = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    if training == "train":
        model.train()
    elif training == "validation":
        model.eval()
    elif training == "test":
        model.eval()
    else:
        raise ValueError("training argument must be either 'train', 'validation' or 'test'")
        
    total = 0
    correct = 0
    cumulative_loss = 0
    prediction_list = []
    label_list = []
    sigmoid = torch.nn.Sigmoid()
    for sample in dataloader:
   
        data, targets = sample[0].float().to(device), sample[1].type(torch.LongTensor).to(device)
        output = model(data)
        loss_value = loss_function(output, targets.unsqueeze(1).float())
        cumulative_loss += loss_value.item()

        if training == "train":
            optimizer.zero_grad()
            loss_value.backward()
            optimizer.step()
        
        predictions = [round(x) for x in sigmoid(output).to('cpu').detach().squeeze(1).numpy().tolist()]#.argmax(axis=1) # was necessary for multi-class classification
        target_labels = targets.to('cpu').detach().numpy()
        total += len(predictions)
        correct += accuracy_score(target_labels, predictions, normalize=False)
        prediction_list.extend(predictions)
        label_list.extend(target_labels)
    if training == "test":
        return label_list, prediction_list
    f1 = f1_score(label_list, prediction_list)
    accuracy = accuracy_score(label_list, prediction_list)
    confusion = confusion_matrix(label_list, prediction_list)

    return cumulative_loss, accuracy, f1, confusion

In [7]:
class TuneableModel(torch.nn.Module):
    def __init__(self, input_size, layer_size, dropout_rate, n_layers):
        super(TuneableModel, self).__init__()
        self.n_layers = n_layers
        self.input_layer = torch.nn.LazyLinear(layer_size) # input_size inferred from input tensor
        self.linear2 = torch.nn.Linear(layer_size, layer_size)
        self.linear3 = torch.nn.Linear(layer_size, layer_size)
        self.linear4 = torch.nn.Linear(layer_size, layer_size)
        self.linear5 = torch.nn.Linear(layer_size, layer_size)
        self.linear6 = torch.nn.Linear(layer_size, layer_size)
        self.linear7 = torch.nn.Linear(layer_size, layer_size)
        self.linear8 = torch.nn.Linear(layer_size, layer_size)
        self.linear9 = torch.nn.Linear(layer_size, layer_size)
        self.linear10 = torch.nn.Linear(layer_size, layer_size)
        self.output_layer = torch.nn.Linear(layer_size, 1)
        self.dropout = torch.nn.Dropout(dropout_rate)
        self.activation = torch.nn.LeakyReLU()
        self.batchnorm = torch.nn.BatchNorm1d(layer_size)

    def forward(self, x):
        x = self.input_layer(x)
        #x = self.batchnorm(x) # batchnorm layer didn't improve performance
        x = self.activation(x)
        x = self.dropout(x)
        if self.n_layers > 1:
            x = self.linear2(x)
            x = self.activation(x)
            x = self.dropout(x)
            if self.n_layers > 2:
                x = self.linear3(x)
                x = self.activation(x)
                x = self.dropout(x)
                if self.n_layers > 3:
                    x = self.linear4(x)
                    x = self.activation(x)
                    x = self.dropout(x)
                    if self.n_layers > 4:
                        x = self.linear5(x)
                        x = self.activation(x)
                        x = self.dropout(x)
                        if self.n_layers > 5:
                            x = self.linear6(x)
                            x = self.activation(x)
                            x = self.dropout(x)
                            if self.n_layers > 6:
                                x = self.linear7(x)
                                x = self.activation(x)
                                x = self.dropout(x)
                                if self.n_layers > 7:
                                    x = self.linear8(x)
                                    x = self.activation(x)
                                    x = self.dropout(x)
                                    if self.n_layers > 8:
                                        x = self.linear9(x)
                                        x = self.activation(x)
                                        x = self.dropout(x)
                                        if self.n_layers > 9:
                                            x = self.linear10(x)
                                            x = self.activation(x)
                                            x = self.dropout(x)
        x = self.output_layer(x)
        return x

In [8]:
# Training sample
def evaluate(data, parameters, task):
    assert task in [0, 1, 2, 3], "Task argument must be either 1, 2 or 3"
    
    try:
        pos_weight = torch.tensor(parameters["pos_weight"], dtype=torch.float).to(device)
    except:
        pos_weight = None

    max_epochs = 1000

    dataloaders, class_weights = preprocess_and_split_data(data, parameters["batch_size"], task, alpha=parameters["alpha"])

    input_size = 10 # number of features :( -> this is hardcoded for now, try to get it from the dataset
    predictions = []
    labels = []
    torch.manual_seed(seed)
    model = TuneableModel(input_size, parameters["hidden_size"], parameters["dropout"], parameters["n_hidden"])
    model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=parameters["learning_rate"], 
                                  betas=(parameters["beta_1"], parameters["beta_2"]), weight_decay=1e-2)


    
    for i, dataloader in tqdm(enumerate(dataloaders)):
        pos_weight = class_weights[i] if pos_weight is None else pos_weight
        max_patience = 10 if i < 35 else 2
        last_loss = 1000000
        best_epoch = 0
        PATH = f"model_{i}.pt"
        train_dataloader, validation_dataloader, test_dataloader = dataloader[0], dataloader[1], dataloader[2]
        for epoch in range(max_epochs):
            # training
            train_loss, train_accuracy, train_f1, train_confusion = train_test(model, train_dataloader, optimizer, pos_weight, training="train")
            train_loss, train_accuracy, train_f1 = round(train_loss, 2), round(train_accuracy, 4), round(train_f1, 2)
            # validation at end of epoch
            validation_loss, validation_accuracy, validation_f1, validation_confusion = train_test(model, validation_dataloader, optimizer, pos_weight, training="validation")
            validation_loss, validation_accuracy, validation_f1 = round(validation_loss, 2), round(validation_accuracy, 4), round(validation_f1, 2)
            if validation_loss < last_loss:
                last_loss = validation_loss
                best_epoch = epoch
                current_patience = 0
            else:
                if current_patience == 0:
                    torch.save({
                        'epoch': epoch,
                        'model_state_dict': model.state_dict(),
                        'optimizer_state_dict': optimizer.state_dict(),
                        'loss': last_loss,
                        }, PATH)
                current_patience += 1
            if current_patience == max_patience:
                break   

        # Testing once patience is reached
        torch.manual_seed(seed)
        model = TuneableModel(input_size, parameters["hidden_size"], parameters["dropout"], parameters["n_hidden"])
        model.to(device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=parameters["learning_rate"], betas=(0.99, 0.99), weight_decay=1e-4)
        checkpoint = torch.load(PATH)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        prediction_list, label_list = train_test(model, test_dataloader, optimizer, pos_weight, training="test")
        predictions.extend(prediction_list)
        labels.extend(label_list)

    return accuracy_score(labels, predictions), f1_score(labels, predictions), confusion_matrix(labels, predictions)


 ### Parameters:
    Patience = 10
    @ model_params(
        dropout: 0.0
        layer size: 500
        lr: 0.001
        batch_size: 16
        n_layers: 6)
    @ optimizer_AdamW(
        beta_1: 0.999,
        beta_2: 0.999, 
        weight_decay: 1e-2)
    @ BCEWithLogitsLoss(
        pos_weight: vairable)

### Performance:

    Task 1: Known subjects, known items

        Train:Eval:Test - 80:10:10 - 10-fold
            @ alpha = 0.21
        Acc: 98.25%
        F1: 0.9643
        Confusion:
            [[256   4]
            [  2  81]]

        Blind LOOCV: Train:Eval:Test - n-2:1:1
            @ alpha = 0.21
        Acc: 100.0%
        F1: 1.0
        Confusion:
            [[258   0]
            [  0  85]]
            
    Task 2: Left-out subjects, known items
    
        Train:eval:test - 90:10:(1 subject) <- sadface
            @ alpha = 0.21
        Acc: 98.54%
        F1: 0.9701
        Confusion:
            [[257   4]
            [  1  81]]
        
        Train:eval:test - 90:10:(2 subjects)
            @ alpha = 0.21
        Acc: 97.08%
        F1: 0.9405
        Confusion:
            [[254   6]
            [  4  79]]

    Task 3: Left-out items, known subjects, train:eval:test - 90:10:item
            @ pos_weight = 0.8, dropout =0.01
        Acc: 96.5%
        F1: 0.9294
        Confusion:
            [[252   6]
            [  6  79]]

In [9]:

parameters = {
    "dropout": 0.0,
    "hidden_size": 500,
    "learning_rate": 0.001,
    "batch_size": 16,
    "n_hidden": 6,
    "beta_1": 0.999,
    "beta_2": 0.999,
    "alpha": 0.21
}


tasks = ["Known subjects and items, 10-fold CV", "Known subjects and items, LOOCV", "2 Held-out subjects, known items", "1 Held-out items, known subjects"]

for task in [0, 1, 2, 3]:
    if task == 0:
        parameters["alpha"] = 0.21 # 0.21 best so far
        parameters["pos_weight"] = None
    elif task == 1:
        parameters["alpha"] = 0.21
        parameters["pos_weight"] = None
    elif task == 2:
        parameters["alpha"] = 0.19
        parameters["pos_weight"] = None
    elif task == 3:
        parameters["alpha"] = 1
        parameters["pos_weight"] = .8
        parameters["dropout"] = 0.01 # dumb.
        parameters["beta_2"] = 0.99

    print(f"Task: {tasks[task]}")
    print(f'Training on {device} with parameters: \n@ model_params(\n\tdropout={parameters["dropout"]},\
      \n\thidden_size={parameters["hidden_size"]},\n\tlearning_rate={parameters["learning_rate"]},\
      \n\tbatch_size={parameters["batch_size"]},\n\tn_hidden={parameters["n_hidden"]}),')
    print(f'@ optimizer_AdamW(\n\tbeta_1={parameters["beta_1"]},\n\tbeta_2={parameters["beta_2"]})')
    print(f'@ BCEWithLogitsLoss(\n\talpha={parameters["alpha"]})\n')
    accuracy, f1, confusion = evaluate(data, parameters, task)
    print(f"Acc: {round(accuracy*100,2)}%\nF1: {round(f1,4)}")
    print("Confusion:\n", confusion, "\n")

Training on cuda with parameters: 
@ model_params(
	dropout=0.0,      
	hidden_size=500,
	learning_rate=0.001,      
	batch_size=16,
	n_hidden=6),
@ optimizer_AdamW(
	beta_1=0.999,
	beta_2=0.999)
@ BCEWithLogitsLoss(
	alpha=0.21)

Task: Known subjects and items, 10-fold CV


10it [00:23,  2.32s/it]


Acc: 98.25%
F1: 0.9643
Confusion:
 [[256   4]
 [  2  81]]
Training on cuda with parameters: 
@ model_params(
	dropout=0.0,      
	hidden_size=500,
	learning_rate=0.001,      
	batch_size=16,
	n_hidden=6),
@ optimizer_AdamW(
	beta_1=0.999,
	beta_2=0.999)
@ BCEWithLogitsLoss(
	alpha=0.21)

Task: Known subjects and items, LOOCV


12it [00:26,  2.17s/it]